--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NurAzliYT/Form-API
build-by-default: true
branches:
- master
projects:
  Form-API:
    path: ""
    model: virion
    type: library
...
